"""add prompt_template_id to tasks

Revision ID: 66241ccb7b97
Revises: 
Create Date: 2026-07-09 07:55:31.612469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66241ccb7b97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('antibody_candidates', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('antibody_candidates', 'failure_record_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('antibody_candidates', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('antibody_candidates', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False,
               existing_server_default=sa.text("'unknown'"))
    op.alter_column('antibody_candidates', 'severity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('antibody_candidates', 'root_cause',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('antibody_candidates', 'proposed_antibody',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('antibody_candidates', 'proposed_vaccine',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('antibody_candidates', 'proposed_catalyst',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('antibody_candidates', 'confidence_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('(0.5)'))
    op.alter_column('antibody_candidates', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('antibody_candidates', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False,
               existing_server_default=sa.text("'auto-classify'"))
    op.alter_column('antibody_candidates', 'signature',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('antibody_candidates', 'rejection_reason',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('antibody_candidates', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('antibody_candidates', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('antibody_candidates', 'approved_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('tasks', sa.Column('prompt_template_id', sa.String(length=36), nullable=True))
    op.alter_column('tasks', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_foreign_key(None, 'tasks', 'prompt_templates', ['prompt_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('tasks', 'prompt_template_id')
    op.alter_column('antibody_candidates', 'approved_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('antibody_candidates', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('antibody_candidates', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('antibody_candidates', 'rejection_reason',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('antibody_candidates', 'signature',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('antibody_candidates', 'source',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'auto-classify'"))
    op.alter_column('antibody_candidates', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('antibody_candidates', 'confidence_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(0.5)'))
    op.alter_column('antibody_candidates', 'proposed_catalyst',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('antibody_candidates', 'proposed_vaccine',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('antibody_candidates', 'proposed_antibody',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('antibody_candidates', 'root_cause',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('antibody_candidates', 'severity',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('antibody_candidates', 'category',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'unknown'"))
    op.alter_column('antibody_candidates', 'title',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('antibody_candidates', 'failure_record_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('antibody_candidates', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
